# Generated by Django 3.2.8 on 2022-01-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(choices=[(0, 'ROOM 1'), (1, 'ROOM 2'), (2, 'ROOM 3'), (3, 'ROOM 4'), (4, 'ROOM 5')])),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('time', models.IntegerField(choices=[(0, '8-9'), (1, '9-10'), (2, '10-11'), (3, '11-12'), (4, '12-13'), (5, '13-14'), (1, '14-15'), (2, '16-17')])),
                ('invitees', models.ManyToManyField(to='home.User')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_reservations', to='home.user')),
            ],
        ),
    ]
