# Generated by Django 3.2.8 on 2022-01-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
