# Generated by Django 3.2.8 on 2022-01-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.IntegerField(choices=[(0, '8-9'), (1, '9-10'), (2, '10-11'), (3, '11-12'), (4, '12-13'), (5, '13-14'), (6, '14-15'), (7, '16-17')]),
        ),
    ]
