# Generated by Django 3.2.8 on 2022-01-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220118_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
