# Generated by Django 3.2.8 on 2022-01-18 05:47

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_info_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user_info',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
