# Generated by Django 3.2.8 on 2022-01-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_info_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user_info',
            managers=[
            ],
        ),
    ]
