# Generated by Django 3.2.8 on 2022-01-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_user_info_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='指定是否使用者可以登入此管理網站。', verbose_name='工作人員狀態'),
        ),
    ]
